[build]
command = "npm run build"
publish = "build/client"

[functions]
included_files = ["posts/**"]

[dev]
command = "npm run dev"
targetPort = 3000

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=60, s-maxage=60"
